openapi: 3.0.0
info:
  title: Домен ФЛ
  description: Домен данных о ФЛ
  version: 1.0.0
components:
  schemas:
 
    ExternalReference:
      type: object
      description: Ссылка на внешний источник (например профиль в VK)
      properties:
        href:
          type: string
        type:
          type: string
    OtherName:
      type: object
      properties:
        title:
          type: string
        givenName:
          type: string
        familyName:
          type: string
        middleName:
          type: string
        fullName:
          type: string
        formattedName:
          type: string
        validFor:
          $ref: 'https://api.swaggerhub.com/domains/ArtemIvlev/common/1.0.0#/components/schemas/ValidFor'
        nameType:
          type: string
        tradingName:
          type: string
    PartyRole:
      type: object
      description: The part played by a party in a given context.
      properties:
        id:
          type: string
          description: Unique identifier for PartyRoles
        href:
          type: string
          description: Url used to reference the party role.
        name:
          type: string
          description: 'A word, term, or phrase by which the PartyRole is known and distinguished from other PartyRoles.'
        status:
          type: string
          description: Used to track the lifecycle status of the party role.
        statusReason:
          type: string
          description: 'A string providing an explanation on the value of the status lifecycle. For instance if the status is Rejected, statusReason will provide the reason for rejection.'
        account:
          type: array
          items:
            $ref: '#/components/schemas/AccountRef'
        agreement:
          type: array
          items:
            $ref: '#/components/schemas/AgreementRef'
        characteristic:
          type: array
          items:
            $ref: '#/components/schemas/Characteristic'
          description: Describes the characteristic of a party role.
        engagedParty:
          $ref: '#/components/schemas/RelatedParty'
        relatedParty:
          type: array
          items:
            $ref: '#/components/schemas/RelatedParty'
        validFor:
          $ref: '#/components/schemas/TimePeriod'
          description: The time period that the PartyRole is valid for.
        '@baseType':
          type: string
          description: 'When sub-classing, this defines the super-class'
        '@schemaLocation':
          type: string
          format: uri
          description: A URI to a JSON-Schema file that defines additional attributes and relationships
        '@type':
          type: string
          description: 'When sub-classing, this defines the sub-class entity name'
    AccountRef:
      type: object
      description: Account reference. A account may be a party account or a financial account.
      required:
        - name
      properties:
        id:
          type: string
          description: Unique identifier of the account
        href:
          type: string
          description: Reference of the account
        description:
          type: string
          description: Detailed description of the account
        name:
          type: string
          description: Name of the account
        '@baseType':
          type: string
          description: 'When sub-classing, this defines the super-class'
        '@schemaLocation':
          type: string
          format: uri
          description: A URI to a JSON-Schema file that defines additional attributes and relationships
        '@type':
          type: string
          description: 'When sub-classing, this defines the sub-class entity name'
        '@referredType':
          type: string
          description: The actual type of the target instance when needed for disambiguation.
      x-examples: {}
    AgreementRef:
      type: object
      description: 'Agreement reference. An agreement represents a contract or arrangement, either written or verbal and sometimes enforceable by law, such as a service level agreement or a customer price agreement. An agreement involves a number of other business entities, such as products, services, and resources and/or their specifications.'
      properties:
        id:
          type: string
          description: Unique identifier of a related entity.
        href:
          type: string
          description: Reference of the related entity.
        name:
          type: string
          description: Name of the agreement
        '@baseType':
          type: string
          description: 'When sub-classing, this defines the super-class'
        '@schemaLocation':
          type: string
          format: uri
          description: A URI to a JSON-Schema file that defines additional attributes and relationships
        '@type':
          type: string
          description: 'When sub-classing, this defines the sub-class entity name'
        '@referredType':
          type: string
          description: The actual type of the target instance when needed for disambiguation.
      required:
        - id
    Characteristic:
      type: object
      description: Describes a given characteristic of an object or entity through a name/value pair.
      required:
        - name
        - value
      properties:
        name:
          type: string
          description: Name of the characteristic
        valueType:
          type: string
          description: Data type of the value of the characteristic
        value:
          description: The value of the characteristic
        '@baseType':
          type: string
          description: 'When sub-classing, this defines the super-class'
        '@schemaLocation':
          type: string
          format: uri
          description: A URI to a JSON-Schema file that defines additional attributes and relationships
        '@type':
          type: string
          description: 'When sub-classing, this defines the sub-class entity name'
    RelatedParty:
      type: object
      description: Related Entity reference. A related party defines party or party role linked to a specific entity.
      required:
        - '@referredType'
        - id
      properties:
        id:
          type: string
          description: Unique identifier of a related entity.
        href:
          type: string
          description: Reference of the related entity.
        name:
          type: string
          description: Name of the related entity.
        role:
          type: string
          description: Role played by the related party
        '@baseType':
          type: string
          description: 'When sub-classing, this defines the super-class'
        '@schemaLocation':
          type: string
          format: uri
          description: A URI to a JSON-Schema file that defines additional attributes and relationships
        '@type':
          type: string
          description: 'When sub-classing, this defines the sub-class entity name'
        '@referredType':
          type: string
          description: The actual type of the target instance when needed for disambiguation.
    TimePeriod:
      type: object
      description: 'A period of time, either as a deadline (endDateTime only) a startDateTime only, or both'
      properties:
        endDateTime:
          type: string
          format: date-time
          description: 'End of the time period, using IETC-RFC-3339 format'
        startDateTime:
          type: string
          format: date-time
          description: 'Start of the time period, using IETC-RFC-3339 format. If you define a start, you must also define an end'
