openapi: 3.0.0
info:
  title: API.v2
  version: '2.0'
  description: Обновленный API Цифрового профиля
  contact:
    name: Artem Ivlev
    email: ivlev@vtb.ru
servers:
  - url: 'http://localhost:3000'
paths:
  '/individuals/{individualIdType}:{individualId}':
    get:
      summary: Individual
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/individual/IndividualPure.yaml
      operationId: get-individuals
      description: Получение данных ФЛ
    parameters:
      - $ref: '#/components/parameters/individualIdType'
      - $ref: '#/components/parameters/individualId'
  '/individuals/{individualIdType}:{individualId}/documents/':
    parameters:
      - $ref: '#/components/parameters/individualIdType'
      - $ref: '#/components/parameters/individualId'
    get:
      summary: Documents list
      tags: []
      responses:
        '200':
          description: Список документов
          content:
            application/json:
              schema:
                $ref: ../models/docs/DocItems.yaml
      operationId: 'get-individuals-individualIdType-:-individualId-documents'
      description: Получение списка документов
  '/individuals/{individualIdType}:{individualId}/documents/{type}':
    parameters:
      - $ref: '#/components/parameters/individualIdType'
      - $ref: '#/components/parameters/individualId'
      - schema:
          type: string
        name: type
        in: path
        required: true
    get:
      summary: Document get
      tags: []
      responses:
        '200':
          description: Документ
          content:
            application/json:
              schema:
                $ref: ../models/docs/Document.yaml
      operationId: 'get-individuals-individualIdType-:-individualId-documents-type'
      description: Получение определенного документа
components:
  schemas: {}
  parameters:
    individualId:
      name: individualId
      in: path
      required: true
      schema:
        type: string
        maxLength: 64
        example: '11111111'
      description: Идентификатор ФЛ
    individualIdType:
      name: individualIdType
      in: path
      required: true
      schema:
        type: string
        enum:
          - mdmid
          - ucn
          - uuid
        maxLength: 16
      description: Тип идентификатора
