openapi: 3.0.0
info:
  title: API.v2
  version: '2.0'
  description: Обновленный API Цифрового профиля
  contact:
    name: Artem Ivlev
    email: ivlev@vtb.ru
servers:
  - url: 'http://localhost:3000'
paths:
  '/individuals/{individualIdType}:{individualId}':
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/individual/IndividualPure.yaml
      operationId: get-individuals
      description: Получение данных ФЛ
    parameters:
      - $ref: '#/components/parameters/individualIdType'
      - $ref: '#/components/parameters/individualId'
components:
  schemas: {}
  parameters:
    individualId:
      name: individualId
      in: path
      required: true
      schema:
        type: string
        maxLength: 128
        example: '11111111'
      description: Идентификатор ФЛ
    individualIdType:
      name: individualIdType
      in: path
      required: true
      schema:
        type: string
        enum:
          - mdmid
          - ucn
          - uuid
        maxLength: 128
      description: Тип идентификатора
